apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-secret
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-secret
  template:
    metadata:
      labels:
        app: app-secret
    spec:
      containers:
        - name: app-secret
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
